require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/quality_projects", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # QualityProject. As you add validations to QualityProject, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      QualityProject.create! valid_attributes
      get quality_projects_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      quality_project = QualityProject.create! valid_attributes
      get quality_project_url(quality_project)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_quality_project_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      quality_project = QualityProject.create! valid_attributes
      get edit_quality_project_url(quality_project)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new QualityProject" do
        expect {
          post quality_projects_url, params: { quality_project: valid_attributes }
        }.to change(QualityProject, :count).by(1)
      end

      it "redirects to the created quality_project" do
        post quality_projects_url, params: { quality_project: valid_attributes }
        expect(response).to redirect_to(quality_project_url(QualityProject.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new QualityProject" do
        expect {
          post quality_projects_url, params: { quality_project: invalid_attributes }
        }.to change(QualityProject, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post quality_projects_url, params: { quality_project: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested quality_project" do
        quality_project = QualityProject.create! valid_attributes
        patch quality_project_url(quality_project), params: { quality_project: new_attributes }
        quality_project.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the quality_project" do
        quality_project = QualityProject.create! valid_attributes
        patch quality_project_url(quality_project), params: { quality_project: new_attributes }
        quality_project.reload
        expect(response).to redirect_to(quality_project_url(quality_project))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        quality_project = QualityProject.create! valid_attributes
        patch quality_project_url(quality_project), params: { quality_project: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested quality_project" do
      quality_project = QualityProject.create! valid_attributes
      expect {
        delete quality_project_url(quality_project)
      }.to change(QualityProject, :count).by(-1)
    end

    it "redirects to the quality_projects list" do
      quality_project = QualityProject.create! valid_attributes
      delete quality_project_url(quality_project)
      expect(response).to redirect_to(quality_projects_url)
    end
  end
end
